### ISSUE TITLE
Account registration

### ISSUE THREAD

**Issue by sebika** [sebika/dogebank#14]
When a new user requests an account we shouldn't create an entry in the `Client` table. The entry should be created after a Helpdesk user accepts the request.

Related to #12

**Comment by Jokeswar** [comment]
This would imply that the `AccountCreationRequest` holds the same fields as the Client model i.e. duplication of code. I suggest that we abandon this path. Is it ok to close this issue? @sebika

**Comment by sebika** [comment]
Yes, you are right. :+1:
